---
name: lite push check

# on:
#   push:
#     branches-ignore:
#       - main
#   pull_request:
#     types:
#       - closed
#     branches-ignore:
#       - main

on:
  push:
    branches-ignore:
      - main
  pull_request: null


env:
  ENABLE_LINTERS: cspell, lychee, markdownlint, markdown-link-check, markdown-table-formatter

permissions:
  contents: write

concurrency:
  group: megalinter-lite-${{ github.ref }}
  cancel-in-progress: true

jobs:
  megalinter-lite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          # ref: ${{ inputs.branch }}

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@1fc052d03c7a43c78fe0fee19c9d648b749e0c01 #v8.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache MegaLinter Dependencies
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2.0
        with:
          path: ~/.cache
          key: ${{ runner.os }}-megalinter-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-megalinter-
