---
name: megalinter-lite

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch or ref to validate.'
        required: true
        type: string

permissions:
  contents: write

jobs:
  megalinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@1fc052d03c7a43c78fe0fee19c9d648b749e0c01 #v8.3.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ inputs.branch == 'refs/heads/main' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
