name: MegaLinter

on:
  push:
  pull_request:
    branches:
      - main

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit
  REPOSITORY_TRUFFLEHOG_ARGUMENTS: "--exclude-paths=./.github/workflows/linters/trufflehog/exclude-paths.txt"
  REPOSITORY_GIT_DIFF_ARGUMENTS: "--ignore-space-at-eol"
  SPELL_LYCHEE_ARGUMENTS: '--exclude "marketplace\.visualstudio\.com"|"search\.maven\.org"'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: MegaLinter
        uses: oxsecurity/megalinter@1fc052d03c7a43c78fe0fee19c9d648b749e0c01 # v8.3.0
        id: ml
        env:
          VALIDATE_ALL_CODEBASE: >-
            ${{
              github.event_name == 'push' &&
              contains(fromJSON('["refs/heads/main"]'), github.ref)
            }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive MegaLinter Reports
        if: success() || failure()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: megalinter-reports
          path: |
            megalinter-reports
            mega-linter.log
